
stages:
  - prepare
  - deploy

prepare:
  stage: prepare
  image:  ubuntu:latest
  script:
  - apt-get update
  - apt-get install -y mecab mecab-ipadic-utf8 libmecab-dev swig fonts-ipaexfont python3-pip
  - cp /etc/mecabrc /usr/local/etc/
  - pip3 install -r requirements.txt
  - python3 ./get_gitlab_discussion.py 'https://api.github.com/repos/hashicorp/terraform/issues/comments?per_page=100&page='
  - mv wordcloud.png src/
  artifacts:
    paths:
    - src

pages:
  stage: deploy
  image: node:latest
  script:
  - yarn
  - yarn build
  artifacts:
    paths:
    - build