name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare Environment
      run:  |
        apt-get install -y mecab libmecab-dev mecab-ipadic-utf8 swig python3-pip
        pip3 install -r requirements.txt

    - name: Create WordCloud
      run: python ./get_gitlab_discussion.py


